### PR TITLE
Use print function for Python3 compatibility.

### PR DESCRIPTION
**Pull request by umairwaheed**

### CODE REVIEW

**Comment by umairwaheed** [comment]
@crito, can you please review this PR? It modifies the code to use `print` function instead of print statement; this makes the code Python 3 compatible. Thanks.

**Comment by timabbott** [comment]
@crito @bastichelaar we're using this great package for the Zulip test suite (https://github.com/zulip/zulip), but since we're Python 3, we're having to use a fork of your project; I'd much rather have there be a release we can use.  Can you do an upload with this PR included?  

Alternatively, if you don't have time for this package anymore and are OK with us adopting this, we'd be happy to do so.

**Comment by timabbott** [comment]
@crito @bastichelaar just following up on this; would it be possible for us to adopt this package?

**Comment by bastichelaar** [comment]
Hi Tim, I'm fine with you adopting the package. I don't use it at all. Sorry not merging this PR. Let me know how you guys wanna take over the maintenance.

**Comment by timabbott** [comment]
Awesome!  If you can transfer ownership in pypi to me (tabbott) and transfer this repository to me, I'll move it to zulip/fakeldap (in our organization) and the Zulip team can take care of getting a release out (etc.).

**Comment by timabbott** [comment]
@bastichelaar thanks for transferring the project; it's now at zulip/fakeldap.  Can you also give me pypi access so I can upload a release?

**Comment by bastichelaar** [comment]
Hi Tim, I don't have access to the PyPi project. You should ask @crito (https://github.com/crito).

**Comment by timabbott** [comment]
@bastichelaar can you email me his contact information at tabbott@zulipchat.com so I can try contacting him in another medium?  He seems to not be responsive on GitHub.

**Pull request merged**
